### ISSUE TITLE
Inserting SICD into NITF Problem

### ISSUE THREAD

**Issue by jwsv61099** [ngageoint/MATLAB_SAR#10]
Hi there,

I received a NITF which does not have a CMETAA TRE. I'm attempting to use MATLAB SAR to instead convert the existing TREs into a SICD so it can be read into our software. Everything is working so far, and I'm able to insert fields that don't exist when the program complains. 

For example:

```
sicdMetaData = nitfReader.get_meta();
% Missing the Image plane, so it needs to be inserted
sicdMetaData.Grid.ImagePlane = 'GROUND';
% Missing COAPoly
sicdMetaData.Grid.TimeCOAPoly = struct('Coef', 0);
```

The problem here is that I suddenly get a warning saying:
"lineNumber 65: columnNumber: 16, cvc-complex-type.4: Attribute 'exponent1' must appear on element 'Coef'"

Now I looked at the source code for where this error is coming from, and even looked at the SICD Schema, and I understand that Coef  literally needs the attribute exponent1.... so how would I add an attribute to the siceMetaData in this instance?

Thanks!

**Comment by utwade** [comment]
I will assume that 0 is notional rather than an actual value, since TimeCOAPoly really can't be 0 (without some negative times involved), but given that, you should just be able to do this:

sicdMetaData.Grid.TimeCOAPoly = 0;

Don't worry about the XML attributes.  The code will put those in as appropriate without you explicitly worrying about them.
