### ISSUE TITLE
phase history data CPHD file format

### ISSUE THREAD

**Issue by woundednun** [ngageoint/MATLAB_SAR#5]
Hey, I'm working on a project to collect my own SAR data with a radar chip moving along a track. I would like to process my data using the polar format algorithm, so I was looking at the pfa_file.m script to do so. Is there a reference material on how to format my data to be processed by the script? Thanks for any help you can give!

**Comment by utwade** [comment]
Its written to an earlier (and simpler) version of the CPHD spec that can be found here:

https://nsgreg.nga.mil/doc/view?i=4638
https://nsgreg.nga.mil/doc/view?i=4639

We are in the process now of updating the code to the newest spec.  Hope to have it out shortly.  Will leave this issue open until we push that update.

**Comment by Sophilyplum** [comment]
> Hey, I'm working on a project to collect my own SAR data with a radar chip moving along a track. I would like to process my data using the polar format algorithm, so I was looking at the pfa_file.m script to do so. Is there a reference material on how to format my data to be processed by the script? Thanks for any help you can give!

@woundednun I don't know if your issue is that you are unable to read CPHD 0.3 files? but I was able to read one with a slight change to the script **open_ph_reader.m**, code line 66: 
`readerobj = eval("open_" + format_string + "_reader('" + filename + "', varargin{:});");`

This is for MATLAB R2020a. Not sure if useful, @utwade?

**Comment by utwade** [comment]
Maybe I'm confused.  Aren't the new and old versions of that line the same?

The following is true in 2018b and 2021b.

strcmp("test"+"123",['test' '123'])

Sorry, I'm delinquent in pushing the CPHD updates, but it should be out next week.

**Comment by Sophilyplum** [comment]
> Sorry, I'm delinquent in pushing the CPHD updates, but it should be out next week.

That's wonderful @utwade, thank you for the update! 

>strcmp("test"+"123",['test' '123']) 

This compares the output, but not the way the two strings are defined. 

My comment was a suggestion in case they were using double quotes instead of single. As a user, you cannot do a mix of two in your wrapper code where you call an IO scripts such as **open_cphd_data.m**. Best way to test what I mean is to run  
```
path_to_file = "/some/path/to/file"; 
open_cphd_data.m(path_to_file)
```

This returns an error. Sadly in my case, changing the **open_cphd_data.m** was easier than changing the script I need to use for reading the data.

**Comment by utwade** [comment]
Code has all been update to the latest CPHD version.
